name: Deploy Hugo Site to Github Pages on Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/checkout@v1  # v2 does not have submodules option now
       # with:
       #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.2'  # 注意版本
          # extended: true

      - name: Build
        #run: hugo --minify
        run: hugo --minify
        #run: |
        #  cd starter-academic
        #  hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: Lihui-Wang/Lihui-Wang.github.io # Pages 远程仓库
          # publish_dir: "./starter-academic/public/"
          publish_dir: "./public/"
          keep_files: true # remove existing files
          publish_branch: main  # deploying branch
          commit_message: ${{ github.event.head_commit.message }}
