permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.2'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}           # ← 必须是 personal_token
          external_repository: Lihui-Wang/Lihui-Wang.github.io # ← 目标仓库（注意大小写/斜杠）
          publish_branch: main                                 # ← 目标仓库的分支
          publish_dir: ./public/
          keep_files: false
          commit_message: ${{ github.event.head_commit.message }}
